name: Build HealthGPS (release)

description: Build HealthGPS (release)

runs:
  using: "composite"

  steps:
    - name: Build HealthGPS (release)
      shell: bash
      run: |
        # Build documentation so we can show Doxygen warnings
        cmake --preset=${{ matrix.platform }}-release -DWARNINGS_AS_ERRORS=ON -DBUILD_DOC=ON
        cmake --build --preset=release-build-${{ matrix.platform }} --target=install
