var searchData=
[
  ['vcpkg_23329',['Vcpkg',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_es.html',1,'']]],
  ['vcpkg_20and_20android_23330',['Vcpkg and Android',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_users_android.html',1,'']]],
  ['vcpkg_20and_20mingw_2dw64_23331',['Vcpkg and Mingw-w64',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_users_mingw.html',1,'']]],
  ['vcpkg_20install_23332',['vcpkg install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_install.html',1,'']]],
  ['vcpkg_20integrate_23333',['vcpkg integrate',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_integrate.html',1,'']]],
  ['vcpkg_20list_23334',['vcpkg list',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_list.html',1,'']]],
  ['vcpkg_20pr_20checklist_23335',['Vcpkg PR Checklist',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_pr_review_checklist.html',1,'']]],
  ['vcpkg_20remove_23336',['vcpkg remove',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_remove.html',1,'']]],
  ['vcpkg_20search_23337',['vcpkg search',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_search.html',1,'']]],
  ['vcpkg_20telemetry_20and_20privacy_23338',['Vcpkg Telemetry and Privacy',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_about_privacy.html',1,'']]],
  ['vcpkg_20version_23339',['vcpkg version',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_version.html',1,'']]],
  ['vcpkg_20x_2dupdate_2dbaseline_23340',['vcpkg x-update-baseline',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_update_baseline.html',1,'']]],
  ['vcpkg_2dcmake_23341',['vcpkg-cmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake.html',1,'']]],
  ['vcpkg_2dcmake_2dconfig_23342',['vcpkg-cmake-config',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake_config.html',1,'']]],
  ['vcpkg_2dcmake_2dget_2dvars_23343',['vcpkg-cmake-get-vars',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_2dget_2dpython_2dpackages_23344',['vcpkg-get-python-packages',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_get_python_packages.html',1,'']]],
  ['vcpkg_2dgn_23345',['vcpkg-gn',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_gn.html',1,'']]],
  ['vcpkg_2dpkgconfig_2dget_2dmodules_23346',['vcpkg-pkgconfig-get-modules',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_pkgconfig_get_modules.html',1,'']]],
  ['vcpkg_2dqmake_23347',['vcpkg-qmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_qmake.html',1,'']]],
  ['vcpkg_3a_20export_20android_20prefab_20archives_20_28aar_20files_29_23348',['Vcpkg: export Android prefab Archives (AAR files)',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_specifications_prefab.html',1,'']]],
  ['vcpkg_3a_20overview_23349',['Vcpkg: Overview',['../md__home_runner_work_healthgps_healthgps_vcpkg_README.html',1,'']]],
  ['vcpkg_3a_20visão_20geral_23350',['Vcpkg: visão geral',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_pt.html',1,'']]],
  ['vcpkg_3a_20vue_20d_27ensemble_23351',['Vcpkg: Vue d&apos;ensemble',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_fr.html',1,'']]],
  ['vcpkg_3a_20总览_23352',['Vcpkg: 总览',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_zh_CN.html',1,'']]],
  ['vcpkg_3a_20개요_23353',['Vcpkg: 개요',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_ko_KR.html',1,'']]],
  ['vcpkg_5facquire_5fmsys_23354',['vcpkg_acquire_msys',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_acquire_msys.html',1,'']]],
  ['vcpkg_5fadd_5fto_5fpath_23355',['vcpkg_add_to_path',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_add_to_path.html',1,'']]],
  ['vcpkg_5fapply_5fpatches_23356',['vcpkg_apply_patches',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_apply_patches.html',1,'']]],
  ['vcpkg_5fbackup_5frestore_5fenv_5fvars_23357',['vcpkg_backup_restore_env_vars',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_backup_restore_env_vars.html',1,'']]],
  ['vcpkg_5fbuild_5fcmake_23358',['vcpkg_build_cmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_cmake.html',1,'']]],
  ['vcpkg_5fbuild_5fmake_23359',['vcpkg_build_make',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_make.html',1,'']]],
  ['vcpkg_5fbuild_5fmsbuild_23360',['vcpkg_build_msbuild',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_msbuild.html',1,'']]],
  ['vcpkg_5fbuild_5fninja_23361',['vcpkg_build_ninja',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_ninja.html',1,'']]],
  ['vcpkg_5fbuild_5fnmake_23362',['vcpkg_build_nmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_nmake.html',1,'']]],
  ['vcpkg_5fbuild_5fqmake_23363',['vcpkg_build_qmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_qmake.html',1,'']]],
  ['vcpkg_5fbuildpath_5flength_5fwarning_23364',['vcpkg_buildpath_length_warning',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_buildpath_length_warning.html',1,'']]],
  ['vcpkg_5fcatalog_5frelease_5fprocess_23365',['vcpkg_catalog_release_process',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_internal_vcpkg_catalog_release_process.html',1,'']]],
  ['vcpkg_5fcheck_5ffeatures_23366',['vcpkg_check_features',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_check_features.html',1,'']]],
  ['vcpkg_5fcheck_5flinkage_23367',['vcpkg_check_linkage',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_check_linkage.html',1,'']]],
  ['vcpkg_5fclean_5fexecutables_5fin_5fbin_23368',['vcpkg_clean_executables_in_bin',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_clean_executables_in_bin.html',1,'']]],
  ['vcpkg_5fclean_5fmsbuild_23369',['vcpkg_clean_msbuild',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_clean_msbuild.html',1,'']]],
  ['vcpkg_5fcmake_5fbuild_23370',['vcpkg_cmake_build',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_cmake_build.html',1,'']]],
  ['vcpkg_5fcmake_5fconfig_5ffixup_23371',['vcpkg_cmake_config_fixup',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake_config_vcpkg_cmake_config_fixup.html',1,'']]],
  ['vcpkg_5fcmake_5fconfigure_23372',['vcpkg_cmake_configure',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_cmake_configure.html',1,'']]],
  ['vcpkg_5fcmake_5fget_5fvars_23373',['vcpkg_cmake_get_vars',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake_get_vars_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_5fcmake_5finstall_23374',['vcpkg_cmake_install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_cmake_install.html',1,'']]],
  ['vcpkg_5fcommon_5fdefinitions_23375',['vcpkg_common_definitions',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_common_definitions.html',1,'']]],
  ['vcpkg_5fconfigure_5fcmake_23376',['vcpkg_configure_cmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_cmake.html',1,'']]],
  ['vcpkg_5fconfigure_5fgn_23377',['vcpkg_configure_gn',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_gn.html',1,'']]],
  ['vcpkg_5fconfigure_5fmake_23378',['vcpkg_configure_make',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_make.html',1,'']]],
  ['vcpkg_5fconfigure_5fmeson_23379',['vcpkg_configure_meson',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_meson.html',1,'']]],
  ['vcpkg_5fconfigure_5fqmake_23380',['vcpkg_configure_qmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_qmake.html',1,'']]],
  ['vcpkg_5fcopy_5fpdbs_23381',['vcpkg_copy_pdbs',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_copy_pdbs.html',1,'']]],
  ['vcpkg_5fcopy_5ftool_5fdependencies_23382',['vcpkg_copy_tool_dependencies',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_copy_tool_dependencies.html',1,'']]],
  ['vcpkg_5fcopy_5ftools_23383',['vcpkg_copy_tools',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_copy_tools.html',1,'']]],
  ['vcpkg_5fdownload_5fdistfile_23384',['vcpkg_download_distfile',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_download_distfile.html',1,'']]],
  ['vcpkg_5fexecute_5fbuild_5fprocess_23385',['vcpkg_execute_build_process',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_execute_build_process.html',1,'']]],
  ['vcpkg_5fexecute_5fin_5fdownload_5fmode_23386',['vcpkg_execute_in_download_mode',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_execute_in_download_mode.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_23387',['vcpkg_execute_required_process',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_execute_required_process.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_5frepeat_23388',['vcpkg_execute_required_process_repeat',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_execute_required_process_repeat.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_23389',['vcpkg_extract_source_archive',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_extract_source_archive.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_5fex_23390',['vcpkg_extract_source_archive_ex',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_extract_source_archive_ex.html',1,'']]],
  ['vcpkg_5ffail_5fport_5finstall_23391',['vcpkg_fail_port_install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_fail_port_install.html',1,'']]],
  ['vcpkg_5ffind_5facquire_5fprogram_23392',['vcpkg_find_acquire_program',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_find_acquire_program.html',1,'']]],
  ['vcpkg_5ffind_5ffortran_23393',['vcpkg_find_fortran',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_find_fortran.html',1,'']]],
  ['vcpkg_5ffixup_5fcmake_5ftargets_23394',['vcpkg_fixup_cmake_targets',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_fixup_cmake_targets.html',1,'']]],
  ['vcpkg_5ffixup_5fpkgconfig_23395',['vcpkg_fixup_pkgconfig',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_fixup_pkgconfig.html',1,'']]],
  ['vcpkg_5ffrom_5fbitbucket_23396',['vcpkg_from_bitbucket',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_bitbucket.html',1,'']]],
  ['vcpkg_5ffrom_5fgit_23397',['vcpkg_from_git',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_git.html',1,'']]],
  ['vcpkg_5ffrom_5fgithub_23398',['vcpkg_from_github',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_github.html',1,'']]],
  ['vcpkg_5ffrom_5fgitlab_23399',['vcpkg_from_gitlab',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_gitlab.html',1,'']]],
  ['vcpkg_5ffrom_5fsourceforge_23400',['vcpkg_from_sourceforge',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_sourceforge.html',1,'']]],
  ['vcpkg_5fget_5fprogram_5ffiles_5fplatform_5fbitness_23401',['vcpkg_get_program_files_platform_bitness',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_get_program_files_platform_bitness.html',1,'']]],
  ['vcpkg_5fget_5fwindows_5fsdk_23402',['vcpkg_get_windows_sdk',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_get_windows_sdk.html',1,'']]],
  ['vcpkg_5fgn_5fconfigure_23403',['vcpkg_gn_configure',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_gn_vcpkg_gn_configure.html',1,'']]],
  ['vcpkg_5fgn_5finstall_23404',['vcpkg_gn_install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_gn_vcpkg_gn_install.html',1,'']]],
  ['vcpkg_5fhost_5fpath_5flist_23405',['vcpkg_host_path_list',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_host_path_list.html',1,'']]],
  ['vcpkg_5finstall_5fcmake_23406',['vcpkg_install_cmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_cmake.html',1,'']]],
  ['vcpkg_5finstall_5fcopyright_23407',['vcpkg_install_copyright',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_copyright.html',1,'']]],
  ['vcpkg_5finstall_5fgn_23408',['vcpkg_install_gn',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_gn.html',1,'']]],
  ['vcpkg_5finstall_5fmake_23409',['vcpkg_install_make',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_make.html',1,'']]],
  ['vcpkg_5finstall_5fmeson_23410',['vcpkg_install_meson',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_meson.html',1,'']]],
  ['vcpkg_5finstall_5fmsbuild_23411',['vcpkg_install_msbuild',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_msbuild.html',1,'']]],
  ['vcpkg_5finstall_5fnmake_23412',['vcpkg_install_nmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_nmake.html',1,'']]],
  ['vcpkg_5finstall_5fqmake_23413',['vcpkg_install_qmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_qmake.html',1,'']]],
  ['vcpkg_5flist_23414',['vcpkg_list',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_list.html',1,'']]],
  ['vcpkg_5fminimum_5frequired_23415',['vcpkg_minimum_required',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_minimum_required.html',1,'']]],
  ['vcpkg_5fqmake_5fbuild_23416',['vcpkg_qmake_build',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_qmake_vcpkg_qmake_build.html',1,'']]],
  ['vcpkg_5fqmake_5fconfigure_23417',['vcpkg_qmake_configure',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_qmake_vcpkg_qmake_configure.html',1,'']]],
  ['vcpkg_5fqmake_5finstall_23418',['vcpkg_qmake_install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_qmake_vcpkg_qmake_install.html',1,'']]],
  ['vcpkg_5freplace_5fstring_23419',['vcpkg_replace_string',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_replace_string.html',1,'']]],
  ['vcpkg_5ftool_5frelease_5fprocess_23420',['vcpkg_tool_release_process',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_internal_vcpkg_tool_release_process.html',1,'']]],
  ['versioning_23421',['Versioning',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_users_versioning.html',1,'']]],
  ['versioning_20specification_23422',['Versioning Specification',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_specifications_versioning.html',1,'']]],
  ['versioning_3a_20implementation_20details_23423',['Versioning: Implementation details',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_users_versioning_implementation_details.html',1,'']]]
];
