var searchData=
[
  ['vcpkg_22946',['Vcpkg',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_es.html',1,'']]],
  ['vcpkg_20and_20android_22947',['Vcpkg and Android',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_users_android.html',1,'']]],
  ['vcpkg_20and_20mingw_2dw64_22948',['Vcpkg and Mingw-w64',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_users_mingw.html',1,'']]],
  ['vcpkg_20install_22949',['vcpkg install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_install.html',1,'']]],
  ['vcpkg_20integrate_22950',['vcpkg integrate',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_integrate.html',1,'']]],
  ['vcpkg_20list_22951',['vcpkg list',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_list.html',1,'']]],
  ['vcpkg_20pr_20checklist_22952',['Vcpkg PR Checklist',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_pr_review_checklist.html',1,'']]],
  ['vcpkg_20remove_22953',['vcpkg remove',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_remove.html',1,'']]],
  ['vcpkg_20search_22954',['vcpkg search',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_search.html',1,'']]],
  ['vcpkg_20telemetry_20and_20privacy_22955',['Vcpkg Telemetry and Privacy',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_about_privacy.html',1,'']]],
  ['vcpkg_20version_22956',['vcpkg version',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_version.html',1,'']]],
  ['vcpkg_20x_2dupdate_2dbaseline_22957',['vcpkg x-update-baseline',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_commands_update_baseline.html',1,'']]],
  ['vcpkg_2dcmake_22958',['vcpkg-cmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake.html',1,'']]],
  ['vcpkg_2dcmake_2dconfig_22959',['vcpkg-cmake-config',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake_config.html',1,'']]],
  ['vcpkg_2dcmake_2dget_2dvars_22960',['vcpkg-cmake-get-vars',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_2dget_2dpython_2dpackages_22961',['vcpkg-get-python-packages',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_get_python_packages.html',1,'']]],
  ['vcpkg_2dgn_22962',['vcpkg-gn',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_gn.html',1,'']]],
  ['vcpkg_2dpkgconfig_2dget_2dmodules_22963',['vcpkg-pkgconfig-get-modules',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_pkgconfig_get_modules.html',1,'']]],
  ['vcpkg_2dqmake_22964',['vcpkg-qmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_qmake.html',1,'']]],
  ['vcpkg_3a_20export_20android_20prefab_20archives_20_28aar_20files_29_22965',['Vcpkg: export Android prefab Archives (AAR files)',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_specifications_prefab.html',1,'']]],
  ['vcpkg_3a_20overview_22966',['Vcpkg: Overview',['../md__home_runner_work_healthgps_healthgps_vcpkg_README.html',1,'']]],
  ['vcpkg_3a_20visão_20geral_22967',['Vcpkg: visão geral',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_pt.html',1,'']]],
  ['vcpkg_3a_20vue_20d_27ensemble_22968',['Vcpkg: Vue d&apos;ensemble',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_fr.html',1,'']]],
  ['vcpkg_3a_20总览_22969',['Vcpkg: 总览',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_zh_CN.html',1,'']]],
  ['vcpkg_3a_20개요_22970',['Vcpkg: 개요',['../md__home_runner_work_healthgps_healthgps_vcpkg_README_ko_KR.html',1,'']]],
  ['vcpkg_5facquire_5fmsys_22971',['vcpkg_acquire_msys',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_acquire_msys.html',1,'']]],
  ['vcpkg_5fadd_5fto_5fpath_22972',['vcpkg_add_to_path',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_add_to_path.html',1,'']]],
  ['vcpkg_5fapply_5fpatches_22973',['vcpkg_apply_patches',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_apply_patches.html',1,'']]],
  ['vcpkg_5fbackup_5frestore_5fenv_5fvars_22974',['vcpkg_backup_restore_env_vars',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_backup_restore_env_vars.html',1,'']]],
  ['vcpkg_5fbuild_5fcmake_22975',['vcpkg_build_cmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_cmake.html',1,'']]],
  ['vcpkg_5fbuild_5fmake_22976',['vcpkg_build_make',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_make.html',1,'']]],
  ['vcpkg_5fbuild_5fmsbuild_22977',['vcpkg_build_msbuild',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_msbuild.html',1,'']]],
  ['vcpkg_5fbuild_5fninja_22978',['vcpkg_build_ninja',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_ninja.html',1,'']]],
  ['vcpkg_5fbuild_5fnmake_22979',['vcpkg_build_nmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_nmake.html',1,'']]],
  ['vcpkg_5fbuild_5fqmake_22980',['vcpkg_build_qmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_build_qmake.html',1,'']]],
  ['vcpkg_5fbuildpath_5flength_5fwarning_22981',['vcpkg_buildpath_length_warning',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_buildpath_length_warning.html',1,'']]],
  ['vcpkg_5fcatalog_5frelease_5fprocess_22982',['vcpkg_catalog_release_process',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_internal_vcpkg_catalog_release_process.html',1,'']]],
  ['vcpkg_5fcheck_5ffeatures_22983',['vcpkg_check_features',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_check_features.html',1,'']]],
  ['vcpkg_5fcheck_5flinkage_22984',['vcpkg_check_linkage',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_check_linkage.html',1,'']]],
  ['vcpkg_5fclean_5fexecutables_5fin_5fbin_22985',['vcpkg_clean_executables_in_bin',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_clean_executables_in_bin.html',1,'']]],
  ['vcpkg_5fclean_5fmsbuild_22986',['vcpkg_clean_msbuild',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_clean_msbuild.html',1,'']]],
  ['vcpkg_5fcmake_5fbuild_22987',['vcpkg_cmake_build',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_cmake_build.html',1,'']]],
  ['vcpkg_5fcmake_5fconfig_5ffixup_22988',['vcpkg_cmake_config_fixup',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake_config_vcpkg_cmake_config_fixup.html',1,'']]],
  ['vcpkg_5fcmake_5fconfigure_22989',['vcpkg_cmake_configure',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_cmake_configure.html',1,'']]],
  ['vcpkg_5fcmake_5fget_5fvars_22990',['vcpkg_cmake_get_vars',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_cmake_get_vars_vcpkg_cmake_get_vars.html',1,'']]],
  ['vcpkg_5fcmake_5finstall_22991',['vcpkg_cmake_install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_cmake_install.html',1,'']]],
  ['vcpkg_5fcommon_5fdefinitions_22992',['vcpkg_common_definitions',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_common_definitions.html',1,'']]],
  ['vcpkg_5fconfigure_5fcmake_22993',['vcpkg_configure_cmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_cmake.html',1,'']]],
  ['vcpkg_5fconfigure_5fgn_22994',['vcpkg_configure_gn',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_gn.html',1,'']]],
  ['vcpkg_5fconfigure_5fmake_22995',['vcpkg_configure_make',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_make.html',1,'']]],
  ['vcpkg_5fconfigure_5fmeson_22996',['vcpkg_configure_meson',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_meson.html',1,'']]],
  ['vcpkg_5fconfigure_5fqmake_22997',['vcpkg_configure_qmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_configure_qmake.html',1,'']]],
  ['vcpkg_5fcopy_5fpdbs_22998',['vcpkg_copy_pdbs',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_copy_pdbs.html',1,'']]],
  ['vcpkg_5fcopy_5ftool_5fdependencies_22999',['vcpkg_copy_tool_dependencies',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_copy_tool_dependencies.html',1,'']]],
  ['vcpkg_5fcopy_5ftools_23000',['vcpkg_copy_tools',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_copy_tools.html',1,'']]],
  ['vcpkg_5fdownload_5fdistfile_23001',['vcpkg_download_distfile',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_download_distfile.html',1,'']]],
  ['vcpkg_5fexecute_5fbuild_5fprocess_23002',['vcpkg_execute_build_process',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_execute_build_process.html',1,'']]],
  ['vcpkg_5fexecute_5fin_5fdownload_5fmode_23003',['vcpkg_execute_in_download_mode',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_execute_in_download_mode.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_23004',['vcpkg_execute_required_process',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_execute_required_process.html',1,'']]],
  ['vcpkg_5fexecute_5frequired_5fprocess_5frepeat_23005',['vcpkg_execute_required_process_repeat',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_execute_required_process_repeat.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_23006',['vcpkg_extract_source_archive',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_extract_source_archive.html',1,'']]],
  ['vcpkg_5fextract_5fsource_5farchive_5fex_23007',['vcpkg_extract_source_archive_ex',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_extract_source_archive_ex.html',1,'']]],
  ['vcpkg_5ffail_5fport_5finstall_23008',['vcpkg_fail_port_install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_fail_port_install.html',1,'']]],
  ['vcpkg_5ffind_5facquire_5fprogram_23009',['vcpkg_find_acquire_program',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_find_acquire_program.html',1,'']]],
  ['vcpkg_5ffind_5ffortran_23010',['vcpkg_find_fortran',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_find_fortran.html',1,'']]],
  ['vcpkg_5ffixup_5fcmake_5ftargets_23011',['vcpkg_fixup_cmake_targets',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_fixup_cmake_targets.html',1,'']]],
  ['vcpkg_5ffixup_5fpkgconfig_23012',['vcpkg_fixup_pkgconfig',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_fixup_pkgconfig.html',1,'']]],
  ['vcpkg_5ffrom_5fbitbucket_23013',['vcpkg_from_bitbucket',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_bitbucket.html',1,'']]],
  ['vcpkg_5ffrom_5fgit_23014',['vcpkg_from_git',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_git.html',1,'']]],
  ['vcpkg_5ffrom_5fgithub_23015',['vcpkg_from_github',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_github.html',1,'']]],
  ['vcpkg_5ffrom_5fgitlab_23016',['vcpkg_from_gitlab',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_gitlab.html',1,'']]],
  ['vcpkg_5ffrom_5fsourceforge_23017',['vcpkg_from_sourceforge',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_from_sourceforge.html',1,'']]],
  ['vcpkg_5fget_5fprogram_5ffiles_5fplatform_5fbitness_23018',['vcpkg_get_program_files_platform_bitness',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_get_program_files_platform_bitness.html',1,'']]],
  ['vcpkg_5fget_5fwindows_5fsdk_23019',['vcpkg_get_windows_sdk',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_get_windows_sdk.html',1,'']]],
  ['vcpkg_5fgn_5fconfigure_23020',['vcpkg_gn_configure',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_gn_vcpkg_gn_configure.html',1,'']]],
  ['vcpkg_5fgn_5finstall_23021',['vcpkg_gn_install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_gn_vcpkg_gn_install.html',1,'']]],
  ['vcpkg_5fhost_5fpath_5flist_23022',['vcpkg_host_path_list',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_host_path_list.html',1,'']]],
  ['vcpkg_5finstall_5fcmake_23023',['vcpkg_install_cmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_cmake.html',1,'']]],
  ['vcpkg_5finstall_5fcopyright_23024',['vcpkg_install_copyright',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_copyright.html',1,'']]],
  ['vcpkg_5finstall_5fgn_23025',['vcpkg_install_gn',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_gn.html',1,'']]],
  ['vcpkg_5finstall_5fmake_23026',['vcpkg_install_make',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_make.html',1,'']]],
  ['vcpkg_5finstall_5fmeson_23027',['vcpkg_install_meson',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_meson.html',1,'']]],
  ['vcpkg_5finstall_5fmsbuild_23028',['vcpkg_install_msbuild',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_msbuild.html',1,'']]],
  ['vcpkg_5finstall_5fnmake_23029',['vcpkg_install_nmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_nmake.html',1,'']]],
  ['vcpkg_5finstall_5fqmake_23030',['vcpkg_install_qmake',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_install_qmake.html',1,'']]],
  ['vcpkg_5flist_23031',['vcpkg_list',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_list.html',1,'']]],
  ['vcpkg_5fminimum_5frequired_23032',['vcpkg_minimum_required',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_minimum_required.html',1,'']]],
  ['vcpkg_5fqmake_5fbuild_23033',['vcpkg_qmake_build',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_qmake_vcpkg_qmake_build.html',1,'']]],
  ['vcpkg_5fqmake_5fconfigure_23034',['vcpkg_qmake_configure',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_qmake_vcpkg_qmake_configure.html',1,'']]],
  ['vcpkg_5fqmake_5finstall_23035',['vcpkg_qmake_install',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_ports_vcpkg_qmake_vcpkg_qmake_install.html',1,'']]],
  ['vcpkg_5freplace_5fstring_23036',['vcpkg_replace_string',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_vcpkg_replace_string.html',1,'']]],
  ['vcpkg_5ftool_5frelease_5fprocess_23037',['vcpkg_tool_release_process',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_maintainers_internal_vcpkg_tool_release_process.html',1,'']]],
  ['versioning_23038',['Versioning',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_users_versioning.html',1,'']]],
  ['versioning_20specification_23039',['Versioning Specification',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_specifications_versioning.html',1,'']]],
  ['versioning_3a_20implementation_20details_23040',['Versioning: Implementation details',['../md__home_runner_work_healthgps_healthgps_vcpkg_docs_users_versioning_implementation_details.html',1,'']]]
];
