var annotated_dup =
[
    [ "hgps", "namespacehgps.html", [
      [ "core", "namespacehgps_1_1core.html", [
        [ "detail", "namespacehgps_1_1core_1_1detail.html", [
          [ "DefaultValueAccessor", "structhgps_1_1core_1_1detail_1_1DefaultValueAccessor.html", "structhgps_1_1core_1_1detail_1_1DefaultValueAccessor" ]
        ] ],
        [ "LifeExpectancyItem", "structhgps_1_1core_1_1LifeExpectancyItem.html", "structhgps_1_1core_1_1LifeExpectancyItem" ],
        [ "DiseaseAnalysisEntity", "structhgps_1_1core_1_1DiseaseAnalysisEntity.html", "structhgps_1_1core_1_1DiseaseAnalysisEntity" ],
        [ "LmsDataRow", "structhgps_1_1core_1_1LmsDataRow.html", "structhgps_1_1core_1_1LmsDataRow" ],
        [ "Array2D", "classhgps_1_1core_1_1Array2D.html", "classhgps_1_1core_1_1Array2D" ],
        [ "DataTableColumn", "classhgps_1_1core_1_1DataTableColumn.html", "classhgps_1_1core_1_1DataTableColumn" ],
        [ "PrimitiveDataTableColumnBuilder", "classhgps_1_1core_1_1PrimitiveDataTableColumnBuilder.html", "classhgps_1_1core_1_1PrimitiveDataTableColumnBuilder" ],
        [ "DataTableColumnIterator", "classhgps_1_1core_1_1DataTableColumnIterator.html", "classhgps_1_1core_1_1DataTableColumnIterator" ],
        [ "FloatDataTableColumn", "classhgps_1_1core_1_1FloatDataTableColumn.html", "classhgps_1_1core_1_1FloatDataTableColumn" ],
        [ "DoubleDataTableColumn", "classhgps_1_1core_1_1DoubleDataTableColumn.html", "classhgps_1_1core_1_1DoubleDataTableColumn" ],
        [ "IntegerDataTableColumn", "classhgps_1_1core_1_1IntegerDataTableColumn.html", "classhgps_1_1core_1_1IntegerDataTableColumn" ],
        [ "PrimitiveDataTableColumn", "classhgps_1_1core_1_1PrimitiveDataTableColumn.html", "classhgps_1_1core_1_1PrimitiveDataTableColumn" ],
        [ "StringDataTableColumn", "classhgps_1_1core_1_1StringDataTableColumn.html", "classhgps_1_1core_1_1StringDataTableColumn" ],
        [ "Country", "structhgps_1_1core_1_1Country.html", "structhgps_1_1core_1_1Country" ],
        [ "Datastore", "classhgps_1_1core_1_1Datastore.html", "classhgps_1_1core_1_1Datastore" ],
        [ "DataTable", "classhgps_1_1core_1_1DataTable.html", "classhgps_1_1core_1_1DataTable" ],
        [ "DiseaseInfo", "structhgps_1_1core_1_1DiseaseInfo.html", "structhgps_1_1core_1_1DiseaseInfo" ],
        [ "DiseaseItem", "structhgps_1_1core_1_1DiseaseItem.html", "structhgps_1_1core_1_1DiseaseItem" ],
        [ "DiseaseEntity", "structhgps_1_1core_1_1DiseaseEntity.html", "structhgps_1_1core_1_1DiseaseEntity" ],
        [ "RelativeRiskEntity", "structhgps_1_1core_1_1RelativeRiskEntity.html", "structhgps_1_1core_1_1RelativeRiskEntity" ],
        [ "CancerParameterEntity", "structhgps_1_1core_1_1CancerParameterEntity.html", "structhgps_1_1core_1_1CancerParameterEntity" ],
        [ "LookupGenderValue", "structhgps_1_1core_1_1LookupGenderValue.html", "structhgps_1_1core_1_1LookupGenderValue" ],
        [ "Identifier", "structhgps_1_1core_1_1Identifier.html", "structhgps_1_1core_1_1Identifier" ],
        [ "BirthItem", "structhgps_1_1core_1_1BirthItem.html", "structhgps_1_1core_1_1BirthItem" ],
        [ "Interval", "classhgps_1_1core_1_1Interval.html", "classhgps_1_1core_1_1Interval" ],
        [ "MathHelper", "classhgps_1_1core_1_1MathHelper.html", "classhgps_1_1core_1_1MathHelper" ],
        [ "MortalityItem", "structhgps_1_1core_1_1MortalityItem.html", "structhgps_1_1core_1_1MortalityItem" ],
        [ "PopulationItem", "structhgps_1_1core_1_1PopulationItem.html", "structhgps_1_1core_1_1PopulationItem" ],
        [ "ScopedTimer", "classhgps_1_1core_1_1ScopedTimer.html", "classhgps_1_1core_1_1ScopedTimer" ],
        [ "case_insensitive", "structhgps_1_1core_1_1case__insensitive.html", "structhgps_1_1core_1_1case__insensitive" ],
        [ "UnivariateSummary", "classhgps_1_1core_1_1UnivariateSummary.html", "classhgps_1_1core_1_1UnivariateSummary" ],
        [ "Version", "classhgps_1_1core_1_1Version.html", "classhgps_1_1core_1_1Version" ],
        [ "DataTableColumnVisitor", "classhgps_1_1core_1_1DataTableColumnVisitor.html", "classhgps_1_1core_1_1DataTableColumnVisitor" ]
      ] ],
      [ "data", "namespacehgps_1_1data.html", [
        [ "DataManager", "classhgps_1_1data_1_1DataManager.html", "classhgps_1_1data_1_1DataManager" ]
      ] ],
      [ "detail", "namespacehgps_1_1detail.html", [
        [ "RelativeRiskInfo", "structhgps_1_1detail_1_1RelativeRiskInfo.html", "structhgps_1_1detail_1_1RelativeRiskInfo" ],
        [ "StoreConverter", "classhgps_1_1detail_1_1StoreConverter.html", "classhgps_1_1detail_1_1StoreConverter" ]
      ] ],
      [ "AnalysisDefinition", "classhgps_1_1AnalysisDefinition.html", "classhgps_1_1AnalysisDefinition" ],
      [ "AnalysisModule", "classhgps_1_1AnalysisModule.html", "classhgps_1_1AnalysisModule" ],
      [ "BaselineScenario", "classhgps_1_1BaselineScenario.html", "classhgps_1_1BaselineScenario" ],
      [ "Channel", "classhgps_1_1Channel.html", "classhgps_1_1Channel" ],
      [ "DataSeries", "classhgps_1_1DataSeries.html", "classhgps_1_1DataSeries" ],
      [ "DefaultCancerModel", "classhgps_1_1DefaultCancerModel.html", "classhgps_1_1DefaultCancerModel" ],
      [ "DefaultDiseaseModel", "classhgps_1_1DefaultDiseaseModel.html", "classhgps_1_1DefaultDiseaseModel" ],
      [ "PopulationRecord", "structhgps_1_1PopulationRecord.html", "structhgps_1_1PopulationRecord" ],
      [ "PopulationModule", "classhgps_1_1PopulationModule.html", "classhgps_1_1PopulationModule" ],
      [ "DiseaseModule", "classhgps_1_1DiseaseModule.html", "classhgps_1_1DiseaseModule" ],
      [ "DiseaseParameter", "structhgps_1_1DiseaseParameter.html", "structhgps_1_1DiseaseParameter" ],
      [ "DiseaseDefinition", "classhgps_1_1DiseaseDefinition.html", "classhgps_1_1DiseaseDefinition" ],
      [ "MeasureKey", "structhgps_1_1MeasureKey.html", null ],
      [ "DiseaseMeasure", "classhgps_1_1DiseaseMeasure.html", "classhgps_1_1DiseaseMeasure" ],
      [ "DiseaseTable", "classhgps_1_1DiseaseTable.html", "classhgps_1_1DiseaseTable" ],
      [ "FactorDynamicEquation", "structhgps_1_1FactorDynamicEquation.html", "structhgps_1_1FactorDynamicEquation" ],
      [ "AgeGroupGenderEquation", "structhgps_1_1AgeGroupGenderEquation.html", "structhgps_1_1AgeGroupGenderEquation" ],
      [ "EnergyBalanceHierarchicalModel", "classhgps_1_1EnergyBalanceHierarchicalModel.html", "classhgps_1_1EnergyBalanceHierarchicalModel" ],
      [ "LiteHierarchicalModelDefinition", "classhgps_1_1LiteHierarchicalModelDefinition.html", "classhgps_1_1LiteHierarchicalModelDefinition" ],
      [ "EnergyBalanceModel", "classhgps_1_1EnergyBalanceModel.html", "classhgps_1_1EnergyBalanceModel" ],
      [ "EnergyBalanceModelDefinition", "classhgps_1_1EnergyBalanceModelDefinition.html", "classhgps_1_1EnergyBalanceModelDefinition" ],
      [ "ErrorEventMessage", "structhgps_1_1ErrorEventMessage.html", "structhgps_1_1ErrorEventMessage" ],
      [ "EventHandlerIdentifier", "structhgps_1_1EventHandlerIdentifier.html", "structhgps_1_1EventHandlerIdentifier" ],
      [ "EventSubscriber", "classhgps_1_1EventSubscriber.html", "classhgps_1_1EventSubscriber" ],
      [ "EventAggregator", "classhgps_1_1EventAggregator.html", "classhgps_1_1EventAggregator" ],
      [ "DefaultEventBus", "classhgps_1_1DefaultEventBus.html", "classhgps_1_1DefaultEventBus" ],
      [ "EventMessage", "structhgps_1_1EventMessage.html", "structhgps_1_1EventMessage" ],
      [ "EventSubscriberHandler", "classhgps_1_1EventSubscriberHandler.html", "classhgps_1_1EventSubscriberHandler" ],
      [ "EventMessageVisitor", "classhgps_1_1EventMessageVisitor.html", "classhgps_1_1EventMessageVisitor" ],
      [ "Finally", "classhgps_1_1Finally.html", "classhgps_1_1Finally" ],
      [ "FiscalPolicyDefinition", "structhgps_1_1FiscalPolicyDefinition.html", "structhgps_1_1FiscalPolicyDefinition" ],
      [ "FiscalPolicyScenario", "classhgps_1_1FiscalPolicyScenario.html", "classhgps_1_1FiscalPolicyScenario" ],
      [ "AdjustmentFactor", "structhgps_1_1AdjustmentFactor.html", "structhgps_1_1AdjustmentFactor" ],
      [ "PolicyCoverage", "structhgps_1_1PolicyCoverage.html", "structhgps_1_1PolicyCoverage" ],
      [ "TransferCoefficient", "structhgps_1_1TransferCoefficient.html", "structhgps_1_1TransferCoefficient" ],
      [ "FoodLabellingDefinition", "structhgps_1_1FoodLabellingDefinition.html", "structhgps_1_1FoodLabellingDefinition" ],
      [ "FoodLabellingScenario", "classhgps_1_1FoodLabellingScenario.html", "classhgps_1_1FoodLabellingScenario" ],
      [ "GenderTable", "classhgps_1_1GenderTable.html", "classhgps_1_1GenderTable" ],
      [ "AgeGenderTable", "classhgps_1_1AgeGenderTable.html", "classhgps_1_1AgeGenderTable" ],
      [ "GenderValue", "structhgps_1_1GenderValue.html", "structhgps_1_1GenderValue" ],
      [ "HealthGPS", "classhgps_1_1HealthGPS.html", "classhgps_1_1HealthGPS" ],
      [ "Coefficient", "structhgps_1_1Coefficient.html", "structhgps_1_1Coefficient" ],
      [ "LinearModel", "structhgps_1_1LinearModel.html", "structhgps_1_1LinearModel" ],
      [ "HierarchicalLevel", "structhgps_1_1HierarchicalLevel.html", "structhgps_1_1HierarchicalLevel" ],
      [ "StaticHierarchicalLinearModel", "classhgps_1_1StaticHierarchicalLinearModel.html", "classhgps_1_1StaticHierarchicalLinearModel" ],
      [ "HierarchicalLinearModelDefinition", "classhgps_1_1HierarchicalLinearModelDefinition.html", "classhgps_1_1HierarchicalLinearModelDefinition" ],
      [ "InfoEventMessage", "structhgps_1_1InfoEventMessage.html", "structhgps_1_1InfoEventMessage" ],
      [ "SimulationModule", "classhgps_1_1SimulationModule.html", "classhgps_1_1SimulationModule" ],
      [ "UpdatableModule", "classhgps_1_1UpdatableModule.html", "classhgps_1_1UpdatableModule" ],
      [ "DiseaseHostModule", "classhgps_1_1DiseaseHostModule.html", "classhgps_1_1DiseaseHostModule" ],
      [ "RiskFactorHostModule", "classhgps_1_1RiskFactorHostModule.html", "classhgps_1_1RiskFactorHostModule" ],
      [ "DemographicModule", "classhgps_1_1DemographicModule.html", "classhgps_1_1DemographicModule" ],
      [ "HierarchicalLinearModel", "classhgps_1_1HierarchicalLinearModel.html", "classhgps_1_1HierarchicalLinearModel" ],
      [ "RiskFactorModelDefinition", "classhgps_1_1RiskFactorModelDefinition.html", "classhgps_1_1RiskFactorModelDefinition" ],
      [ "DiseaseModel", "classhgps_1_1DiseaseModel.html", "classhgps_1_1DiseaseModel" ],
      [ "InterventionScenario", "classhgps_1_1InterventionScenario.html", "classhgps_1_1InterventionScenario" ],
      [ "DynamicInterventionScenario", "classhgps_1_1DynamicInterventionScenario.html", "classhgps_1_1DynamicInterventionScenario" ],
      [ "PolicyImpact", "structhgps_1_1PolicyImpact.html", "structhgps_1_1PolicyImpact" ],
      [ "PolicyInterval", "structhgps_1_1PolicyInterval.html", "structhgps_1_1PolicyInterval" ],
      [ "PolicyDynamic", "structhgps_1_1PolicyDynamic.html", "structhgps_1_1PolicyDynamic" ],
      [ "Birth", "structhgps_1_1Birth.html", "structhgps_1_1Birth" ],
      [ "LifeTable", "classhgps_1_1LifeTable.html", "classhgps_1_1LifeTable" ],
      [ "LmsRecord", "structhgps_1_1LmsRecord.html", "structhgps_1_1LmsRecord" ],
      [ "LmsDefinition", "classhgps_1_1LmsDefinition.html", "classhgps_1_1LmsDefinition" ],
      [ "LmsModel", "classhgps_1_1LmsModel.html", "classhgps_1_1LmsModel" ],
      [ "Map2d", "classhgps_1_1Map2d.html", "classhgps_1_1Map2d" ],
      [ "FactorRange", "structhgps_1_1FactorRange.html", "structhgps_1_1FactorRange" ],
      [ "MappingEntry", "classhgps_1_1MappingEntry.html", "classhgps_1_1MappingEntry" ],
      [ "HierarchicalMapping", "classhgps_1_1HierarchicalMapping.html", "classhgps_1_1HierarchicalMapping" ],
      [ "MarketingDynamicDefinition", "structhgps_1_1MarketingDynamicDefinition.html", "structhgps_1_1MarketingDynamicDefinition" ],
      [ "MarketingDynamicScenario", "classhgps_1_1MarketingDynamicScenario.html", "classhgps_1_1MarketingDynamicScenario" ],
      [ "MarketingPolicyDefinition", "structhgps_1_1MarketingPolicyDefinition.html", "structhgps_1_1MarketingPolicyDefinition" ],
      [ "MarketingPolicyScenario", "classhgps_1_1MarketingPolicyScenario.html", "classhgps_1_1MarketingPolicyScenario" ],
      [ "ResultByGender", "structhgps_1_1ResultByGender.html", "structhgps_1_1ResultByGender" ],
      [ "DALYsIndicator", "structhgps_1_1DALYsIndicator.html", "structhgps_1_1DALYsIndicator" ],
      [ "ModelResult", "structhgps_1_1ModelResult.html", "structhgps_1_1ModelResult" ],
      [ "RunInfo", "structhgps_1_1RunInfo.html", "structhgps_1_1RunInfo" ],
      [ "SESDefinition", "structhgps_1_1SESDefinition.html", "structhgps_1_1SESDefinition" ],
      [ "ModelInput", "classhgps_1_1ModelInput.html", "classhgps_1_1ModelInput" ],
      [ "ModelRunner", "classhgps_1_1ModelRunner.html", "classhgps_1_1ModelRunner" ],
      [ "SimulationModuleFactory", "classhgps_1_1SimulationModuleFactory.html", "classhgps_1_1SimulationModuleFactory" ],
      [ "MonotonicVector", "classhgps_1_1MonotonicVector.html", "classhgps_1_1MonotonicVector" ],
      [ "MTRandom32", "classhgps_1_1MTRandom32.html", "classhgps_1_1MTRandom32" ],
      [ "Disease", "structhgps_1_1Disease.html", "structhgps_1_1Disease" ],
      [ "Person", "structhgps_1_1Person.html", "structhgps_1_1Person" ],
      [ "PhysicalActivityDefinition", "structhgps_1_1PhysicalActivityDefinition.html", "structhgps_1_1PhysicalActivityDefinition" ],
      [ "PhysicalActivityScenario", "classhgps_1_1PhysicalActivityScenario.html", "classhgps_1_1PhysicalActivityScenario" ],
      [ "Population", "classhgps_1_1Population.html", "classhgps_1_1Population" ],
      [ "Random", "classhgps_1_1Random.html", "classhgps_1_1Random" ],
      [ "RandomBitGenerator", "classhgps_1_1RandomBitGenerator.html", "classhgps_1_1RandomBitGenerator" ],
      [ "RelativeRiskLookup", "classhgps_1_1RelativeRiskLookup.html", "classhgps_1_1RelativeRiskLookup" ],
      [ "RelativeRisk", "structhgps_1_1RelativeRisk.html", "structhgps_1_1RelativeRisk" ],
      [ "Repository", "classhgps_1_1Repository.html", "classhgps_1_1Repository" ],
      [ "CachedRepository", "classhgps_1_1CachedRepository.html", "classhgps_1_1CachedRepository" ],
      [ "ResultEventMessage", "structhgps_1_1ResultEventMessage.html", "structhgps_1_1ResultEventMessage" ],
      [ "RiskFactorModule", "classhgps_1_1RiskFactorModule.html", "classhgps_1_1RiskFactorModule" ],
      [ "RiskfactorAdjustmentModel", "classhgps_1_1RiskfactorAdjustmentModel.html", "classhgps_1_1RiskfactorAdjustmentModel" ],
      [ "BaselineAdjustment", "structhgps_1_1BaselineAdjustment.html", "structhgps_1_1BaselineAdjustment" ],
      [ "FirstMoment", "structhgps_1_1FirstMoment.html", "structhgps_1_1FirstMoment" ],
      [ "RunnerEventMessage", "structhgps_1_1RunnerEventMessage.html", "structhgps_1_1RunnerEventMessage" ],
      [ "RuntimeContext", "classhgps_1_1RuntimeContext.html", "classhgps_1_1RuntimeContext" ],
      [ "RuntimeMetric", "classhgps_1_1RuntimeMetric.html", "classhgps_1_1RuntimeMetric" ],
      [ "Scenario", "classhgps_1_1Scenario.html", "classhgps_1_1Scenario" ],
      [ "SESNoiseModule", "classhgps_1_1SESNoiseModule.html", "classhgps_1_1SESNoiseModule" ],
      [ "Settings", "classhgps_1_1Settings.html", "classhgps_1_1Settings" ],
      [ "SimplePolicyDefinition", "structhgps_1_1SimplePolicyDefinition.html", "structhgps_1_1SimplePolicyDefinition" ],
      [ "SimplePolicyScenario", "classhgps_1_1SimplePolicyScenario.html", "classhgps_1_1SimplePolicyScenario" ],
      [ "Simulation", "classhgps_1_1Simulation.html", "classhgps_1_1Simulation" ],
      [ "SimulationDefinition", "structhgps_1_1SimulationDefinition.html", "structhgps_1_1SimulationDefinition" ],
      [ "SyncMessage", "classhgps_1_1SyncMessage.html", "classhgps_1_1SyncMessage" ],
      [ "SyncDataMessage", "classhgps_1_1SyncDataMessage.html", "classhgps_1_1SyncDataMessage" ],
      [ "ThreadsafeQueue", "classhgps_1_1ThreadsafeQueue.html", "classhgps_1_1ThreadsafeQueue" ],
      [ "TwoStepValue", "structhgps_1_1TwoStepValue.html", "structhgps_1_1TwoStepValue" ],
      [ "UnivariateVisitor", "classhgps_1_1UnivariateVisitor.html", "classhgps_1_1UnivariateVisitor" ],
      [ "WeightModel", "classhgps_1_1WeightModel.html", "classhgps_1_1WeightModel" ]
    ] ],
    [ "host", "namespacehost.html", [
      [ "poco", "namespacehost_1_1poco.html", [
        [ "FileInfo", "structhost_1_1poco_1_1FileInfo.html", "structhost_1_1poco_1_1FileInfo" ],
        [ "SettingsInfo", "structhost_1_1poco_1_1SettingsInfo.html", "structhost_1_1poco_1_1SettingsInfo" ],
        [ "SESInfo", "structhost_1_1poco_1_1SESInfo.html", "structhost_1_1poco_1_1SESInfo" ],
        [ "BaselineInfo", "structhost_1_1poco_1_1BaselineInfo.html", "structhost_1_1poco_1_1BaselineInfo" ],
        [ "RiskFactorInfo", "structhost_1_1poco_1_1RiskFactorInfo.html", "structhost_1_1poco_1_1RiskFactorInfo" ],
        [ "ModellingInfo", "structhost_1_1poco_1_1ModellingInfo.html", "structhost_1_1poco_1_1ModellingInfo" ],
        [ "OutputInfo", "structhost_1_1poco_1_1OutputInfo.html", "structhost_1_1poco_1_1OutputInfo" ],
        [ "PolicyPeriodInfo", "structhost_1_1poco_1_1PolicyPeriodInfo.html", "structhost_1_1poco_1_1PolicyPeriodInfo" ],
        [ "PolicyImpactInfo", "structhost_1_1poco_1_1PolicyImpactInfo.html", "structhost_1_1poco_1_1PolicyImpactInfo" ],
        [ "PolicyAdjustmentInfo", "structhost_1_1poco_1_1PolicyAdjustmentInfo.html", "structhost_1_1poco_1_1PolicyAdjustmentInfo" ],
        [ "PolicyScenarioInfo", "structhost_1_1poco_1_1PolicyScenarioInfo.html", "structhost_1_1poco_1_1PolicyScenarioInfo" ],
        [ "CoefficientInfo", "structhost_1_1poco_1_1CoefficientInfo.html", "structhost_1_1poco_1_1CoefficientInfo" ],
        [ "LinearModelInfo", "structhost_1_1poco_1_1LinearModelInfo.html", "structhost_1_1poco_1_1LinearModelInfo" ],
        [ "Array2Info", "structhost_1_1poco_1_1Array2Info.html", "structhost_1_1poco_1_1Array2Info" ],
        [ "HierarchicalLevelInfo", "structhost_1_1poco_1_1HierarchicalLevelInfo.html", "structhost_1_1poco_1_1HierarchicalLevelInfo" ],
        [ "HierarchicalModelInfo", "structhost_1_1poco_1_1HierarchicalModelInfo.html", "structhost_1_1poco_1_1HierarchicalModelInfo" ],
        [ "VariableInfo", "structhost_1_1poco_1_1VariableInfo.html", "structhost_1_1poco_1_1VariableInfo" ],
        [ "FactorDynamicEquationInfo", "structhost_1_1poco_1_1FactorDynamicEquationInfo.html", "structhost_1_1poco_1_1FactorDynamicEquationInfo" ],
        [ "LiteHierarchicalModelInfo", "structhost_1_1poco_1_1LiteHierarchicalModelInfo.html", "structhost_1_1poco_1_1LiteHierarchicalModelInfo" ]
      ] ],
      [ "EventMonitor", "classhost_1_1EventMonitor.html", "classhost_1_1EventMonitor" ],
      [ "ExperimentInfo", "structhost_1_1ExperimentInfo.html", "structhost_1_1ExperimentInfo" ],
      [ "CommandOptions", "structhost_1_1CommandOptions.html", "structhost_1_1CommandOptions" ],
      [ "Configuration", "structhost_1_1Configuration.html", "structhost_1_1Configuration" ],
      [ "ResultFileWriter", "classhost_1_1ResultFileWriter.html", "classhost_1_1ResultFileWriter" ],
      [ "ResultWriter", "classhost_1_1ResultWriter.html", "classhost_1_1ResultWriter" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "iterator_traits<::hgps::core::DataTableColumnIterator< ColumnType > >", "structstd_1_1iterator__traits_3_1_1hgps_1_1core_1_1DataTableColumnIterator_3_01ColumnType_01_4_01_4.html", "structstd_1_1iterator__traits_3_1_1hgps_1_1core_1_1DataTableColumnIterator_3_01ColumnType_01_4_01_4" ],
      [ "hash< hgps::core::Identifier >", "structstd_1_1hash_3_01hgps_1_1core_1_1Identifier_01_4.html", "structstd_1_1hash_3_01hgps_1_1core_1_1Identifier_01_4" ]
    ] ]
];