var dir_d2cb4d7268994d5bb552b9ff4076d9cb =
[
    [ "analysis.h", "analysis_8h.html", "analysis_8h" ],
    [ "api.h", "_health_g_p_s_8_core_2api_8h.html", null ],
    [ "array2d.h", "array2d_8h.html", "array2d_8h" ],
    [ "column.h", "column_8h.html", "column_8h" ],
    [ "column_builder.h", "column__builder_8h.html", "column__builder_8h" ],
    [ "column_iterator.h", "column__iterator_8h.html", "column__iterator_8h" ],
    [ "column_numeric.h", "column__numeric_8h.html", "column__numeric_8h" ],
    [ "column_primitive.h", "column__primitive_8h.html", "column__primitive_8h" ],
    [ "country.h", "country_8h.html", "country_8h" ],
    [ "datastore.h", "datastore_8h.html", "datastore_8h" ],
    [ "datatable.cpp", "datatable_8cpp.html", "datatable_8cpp" ],
    [ "datatable.h", "datatable_8h.html", "datatable_8h" ],
    [ "disease.h", "_health_g_p_s_8_core_2disease_8h.html", "_health_g_p_s_8_core_2disease_8h" ],
    [ "forward_type.h", "forward__type_8h.html", "forward__type_8h" ],
    [ "identifier.cpp", "identifier_8cpp.html", "identifier_8cpp" ],
    [ "identifier.h", "identifier_8h.html", "identifier_8h" ],
    [ "indicator.h", "indicator_8h.html", "indicator_8h" ],
    [ "interval.cpp", "interval_8cpp.html", "interval_8cpp" ],
    [ "interval.h", "interval_8h.html", "interval_8h" ],
    [ "math_util.cpp", "math__util_8cpp.html", null ],
    [ "math_util.h", "math__util_8h.html", "math__util_8h" ],
    [ "mortality.h", "mortality_8h.html", "mortality_8h" ],
    [ "poco.h", "poco_8h.html", null ],
    [ "population_item.h", "population__item_8h.html", "population__item_8h" ],
    [ "scoped_timer.h", "scoped__timer_8h.html", "scoped__timer_8h" ],
    [ "string_util.cpp", "string__util_8cpp.html", "string__util_8cpp" ],
    [ "string_util.h", "string__util_8h.html", "string__util_8h" ],
    [ "thread_util.h", "thread__util_8h.html", "thread__util_8h" ],
    [ "univariate_summary.cpp", "univariate__summary_8cpp.html", null ],
    [ "univariate_summary.h", "univariate__summary_8h.html", "univariate__summary_8h" ],
    [ "version.cpp", "version_8cpp.html", null ],
    [ "version.h", "version_8h.html", "version_8h" ],
    [ "visitor.h", "visitor_8h.html", "visitor_8h" ]
];