name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Run CMake Linux Workflow
    
    env:
      VCPKG_ROOT: '../vcpkg'
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      DEBUG_PRESET: 'linux-debug'
      DEBUG_BUILD_PRESET: 'debug-build-linux'
      DEBUG_TEST_PRESET: 'core-test-linux'
      RELEASE_PRESET: 'linux-release'
      RELEASE_BUILD_PRESET: 'release-build-linux'
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up GCC
      id: install_gcc
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - name: Get vcpkg
      id: install_vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2021.05.12
        ./bootstrap-vcpkg.sh -disableMetrics    

    - name: Get Ninja
      id: install_ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Get MSVC Tools
      id: install_MSVC
      uses: ilammy/msvc-dev-cmd@v1
     
    - name: Tool Check
      id: toos_version
      run: |
        ls
        cmake --version
        ninja --version
        ./vcpkg/vcpkg --version
        g++ --version

    - name: Configure debug HealthGPS
      id: cmake_config_debug
      working-directory: ${{github.workspace}}/source
      run: cmake --preset=${{env.DEBUG_PRESET}}        

    - name: Build debug HealthGPS
      id: cmake_build_debug
      working-directory: ${{github.workspace}}/source
      run: cmake --build --preset=${{env.DEBUG_BUILD_PRESET}}
      
    - name: Test debug HealthGPS
      id: ctest_run
      working-directory: ${{github.workspace}}/source
      run: ctest --preset=${{env.DEBUG_TEST_PRESET}}

    - name: Configure release HealthGPS
      id: cmake_config_release
      working-directory: ${{github.workspace}}/source
      run: cmake --preset=${{env.RELEASE_PRESET}}

    - name: Build release HealthGPS
      id: cmake_build_release
      working-directory: ${{github.workspace}}/source
      run: cmake --build --preset=${{env.RELEASE_BUILD_PRESET}}

    - name: Zip output folder
      id: zip_folder
      working-directory: ${{github.workspace}}/source/out/build/${{env.RELEASE_PRESET}}/HealthGPS.Console/
      run: |
        mkdir ${{github.workspace}}/artifact
        7z a -tzip ${{github.workspace}}/artifact/health_gps_linux.zip HealthGPS.Console

    - name: Upload artefacts
      id: upload_zip
      uses: actions/upload-artifact@v2
      with:
        name: health-gps-archive
        path: artifact/health_gps_linux.zip
