name: Windows

on:
  push:
    branches: [ main ]
  release:
    types: [published]
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    name: Run CMake Windows Workflow
    
    env:
      VCPKG_ROOT: 'vcpkg'
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      DEBUG_PRESET: 'x64-debug'
      DEBUG_BUILD_PRESET: 'debug-build-windows'
      DEBUG_TEST_PRESET: 'core-test-windows'
      RELEASE_PRESET: 'x64-release'
      RELEASE_BUILD_PRESET: 'release-build-windows'

    steps:
    - uses: actions/checkout@v2

    - name: Get vcpkg
      id: install_vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2022.09.27
        .\bootstrap-vcpkg.bat -disableMetrics    

    - name: Get Ninja
      id: install_ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Get MSVC Tools
      id: install_MSVC
      uses: ilammy/msvc-dev-cmd@v1
     
    - name: Tool Check
      id: toos_version
      run: |
        ls
        cmake --version
        ninja --version
        ./vcpkg/vcpkg --version
        cl

    - name: Configure debug HealthGPS
      id: cmake_config_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=${{env.DEBUG_PRESET}}

    - name: Build debug HealthGPS
      id: cmake_build_debug
      working-directory: ${{github.workspace}}
      run: cmake --build --preset=${{env.DEBUG_BUILD_PRESET}}
      
    - name: Test debug HealthGPS
      id: ctest_run
      working-directory: ${{github.workspace}}
      run: ctest --preset=${{env.DEBUG_TEST_PRESET}}

    - name: Configure release HealthGPS
      id: cmake_config_release
      working-directory: ${{github.workspace}}
      run: cmake --preset=${{env.RELEASE_PRESET}}

    - name: Build release HealthGPS
      id: cmake_build_release
      working-directory: ${{github.workspace}}
      run: cmake --build --preset=${{env.RELEASE_BUILD_PRESET}}

    - name: Zip output folder
      id: zip_folder
      working-directory: ${{github.workspace}}/out/build/${{env.RELEASE_PRESET}}/src/HealthGPS.Console/
      run: |
        mkdir ${{github.workspace}}/artifact
        7z a -tzip ${{github.workspace}}/artifact/health_gps_win64.zip *.dll *.exe

    - name: Upload artefacts
      id: upload_zip
      uses: actions/upload-artifact@v2
      with:
        name: health-gps-archive
        path: artifact/health_gps_win64.zip
        