name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    env:
      VCPKG_ROOT: '../vcpkg'
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      CONFIG_PRESET: 'x64-debug'
      BUILD_PRESET: 'default-build-windows'
      TEST_PRESET: 'core-test-windows'
      
    steps:
    - uses: actions/checkout@v2

    - name: Get vcpkg
      id: install_vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2021.05.12
        .\bootstrap-vcpkg.bat -disableMetrics    

    - name: Get Ninja
      id: install_ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Get MSVC Tools
      id: install_MSVC
      uses: ilammy/msvc-dev-cmd@v1
     
    - name: Tool Check
      id: toos_version
      run: |
        ls
        cmake --version
        ninja --version
        ./vcpkg/vcpkg --version
        cl

    - name: Configure
      id: cmake_config
      working-directory: ${{github.workspace}}/source
      run: cmake --preset=${{env.CONFIG_PRESET}}
    
    - name: Build
      id: cmake_build
      working-directory: ${{github.workspace}}/source
      run: cmake --build --preset=${{env.BUILD_PRESET}}
      
    - name: Test
      id: ctest_run
      working-directory: ${{github.workspace}}/source
      run: ctest --preset=${{env.TEST_PRESET}}

    - name: Zip output folder
      id: zip_folder
      working-directory: ${{github.workspace}}/source/out/build/${{env.CONFIG_PRESET}}/HealthGPS.Console/
      run: |
        mkdir ${{github.workspace}}/artifact
        7z a -tzip ${{github.workspace}}/artifact/health_gps_win64.zip *.dll *.exe

    - name: Upload artefacts
      id: upload_zip
      uses: actions/upload-artifact@v2
      with:
        name: health-gps-archive
        path: artifact/health_gps_win64.zip

