name: Windows

on:
  push:
    branches: [ main ]
  release:
    types: [published]
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    name: Run CMake Windows Workflow
    
    env:
      VCPKG_ROOT: 'vcpkg'
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      DEBUG_PRESET: 'x64-debug'
      DEBUG_BUILD_PRESET: 'debug-build-windows'
      DEBUG_TEST_PRESET: 'core-test-windows'
      RELEASE_PRESET: 'x64-release'
      RELEASE_BUILD_PRESET: 'release-build-windows'

    steps:
    - uses: actions/checkout@v3

    - name: Set up MSVC
      id: install_MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
          arch: x64

    - name: Install vcpkg
      id: install_vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2022.09.27
        .\bootstrap-vcpkg.bat -disableMetrics    

    - name: Install Ninja
      id: install_ninja
      run: choco install ninja

    - name: Tool Check
      id: toos_version
      run: |
        ls
        cmake --version
        ninja --version
        cl
        ./vcpkg/vcpkg --version

    - name: Configure debug HealthGPS
      id: cmake_config_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=${{env.DEBUG_PRESET}} -DBUILD_BENCHMARKS=ON

    - name: Build debug HealthGPS
      id: cmake_build_debug
      working-directory: ${{github.workspace}}
      run: cmake --build --preset=${{env.DEBUG_BUILD_PRESET}}
      
    - name: Test debug HealthGPS
      id: ctest_run
      working-directory: ${{github.workspace}}
      run: ctest --preset=${{env.DEBUG_TEST_PRESET}}

    - name: Configure release HealthGPS
      id: cmake_config_release
      working-directory: ${{github.workspace}}
      run: cmake --preset=${{env.RELEASE_PRESET}} -DBUILD_BENCHMARKS=ON

    - name: Build release HealthGPS
      id: cmake_build_release
      working-directory: ${{github.workspace}}
      run: cmake --build --preset=${{env.RELEASE_BUILD_PRESET}}

    - name: Install release HealthGPS
      id: cmake_install_release
      working-directory: ${{github.workspace}}
      run: cmake --build --preset=${{env.RELEASE_BUILD_PRESET}} --target install --config Release

    - name: Check installed artefacts
      id: cmake_install_check
      working-directory: ${{github.workspace}}/out/install/${{env.RELEASE_PRESET}}/bin/
      run: ls

    - name: Zip output folder
      id: zip_folder
      working-directory: ${{github.workspace}}/out/install/${{env.RELEASE_PRESET}}/bin/
      run: |
        mkdir ${{github.workspace}}/artifact
        7z a -tzip ${{github.workspace}}/artifact/health_gps_win64.zip fmt*.dll *.Console.exe

    - name: Upload artefacts
      id: upload_zip
      uses: actions/upload-artifact@v3
      with:
        name: health-gps-archive
        path: artifact/health_gps_win64.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: artifact/health_gps_win64.zip
                  